services:
  account-db:
    image: mysql:8.0
    container_name: account-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: accountdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3307:3306"
    networks:
      - microservice-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uuser", "-puserpass" ]
      interval: 10s
      timeout: 5s
      retries: 5
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # Puerto para la comunicación AMQP
      - "15672:15672"   # Puerto para la UI web de administración
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservice-net
  account-service:
    container_name: account-service
    build: ./
    ports:
      - "8082:8082"
    depends_on:
      account-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - microservice-net
networks:
  microservice-net:
    external: true

